#!/bin/bash

# Install Composer dependencies
composer install -d "/var/www/app"

# Deal with the .env file if necessary
if [ ! -f "/var/www/app/.env" ]; then
    # Create .env file
    cat > "/var/www/app/.env" << EOF
APP_NAME=project
APP_ENV=local
APP_KEY=
APP_DEBUG=true
APP_URL=http://project.local

LOG_CHANNEL=single

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE: ghtest
DB_USERNAME: dbadmin
DB_PASSWORD: boredtodeath

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
EOF

    # Generate application key
    php "/var/www/app/artisan" key:generate --ansi
fi

# Database
php "/var/www/app/artisan" migrate