version: '3.9'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./src/app:/var/www/app
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  # App Service
  app:
    build: ./src
    working_dir: /var/www/app
    volumes:
      - ./src/app:/var/www/app
    depends_on:
      mysql:
        condition: service_healthy

  # MySQL Service
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: demo
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

# Volumes
volumes:

  mysqldata: